import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="container">
            <nav>
              <Link href="/">New Drops</Link>
              <Link href="/">Men</Link>
              <Link href="/">Women</Link>
            </nav>
            <div>
              {/* Logo */}
            </div>
            <div>
              <div>
                {/* Search Button */}
              </div>
              <div>
                {/* Contact Icon */}
              </div>
              <div>
                {/* Cart count badge */}
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
